project:
  type: book
  output-dir: docs

book:
  title: "Basics of Statistics and R"
  chapters:
    - index.qmd
    - part: "1: Basics of Statistics"
      chapters:
      - files/1stats_1basics.qmd
      - files/1stats_2datatypes.qmd
      - files/1stats_3sampling.qmd
      - files/1stats_4significance.qmd
    - part: "2: Descriptive Statistics"
      chapters:
      - files/2desc_1basics.qmd
      - files/2desc_2summary.qmd
      - files/2desc_3plots.qmd
    - part: "R: Packages and General Deep Dives"
      chapters:
      - files/R_ggplot.qmd
      - files/R_gitsetup.qmd
      - files/R_gituse.qmd
    - files/references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      body-width: 1000px
  pdf:
    documentclass: scrreprt

editor: visual

