project:
  type: book
  output-dir: docs

book:
  title: "Basics of Statistics and R"
  author: "Johannes Engels"
  chapters:
    - index.qmd
    - part: "1: Basics of Statistics"
      chapters:
      - files/1stats_1basics.qmd
      - files/1stats_2sampling.qmd
    - part: "R: Packages and General Deep Dives"
      chapters:
      - files/R_ggplot.qmd
      - files/R_gitsetup.qmd
      - files/R_gituse.qmd
    - files/references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
    grid:
      body-width: 1000px
  pdf:
    documentclass: scrreprt

editor: visual

